version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  target_branch: 'dev'
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - usename-poezd
  assignees:
    - usename-poezd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
